version: '3.3'

services:
  php:
    # note you need to manually build this image from base dockerfile above FIRST!
    image: donpablonow/yxorp
    build: .
    volumes:
      # used delegated mode here on docker for mac for faster disk I/O
      - .:/var/www/app:delegated
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        # mount in dev certs if you want to dev over ssl
      #- ./dev-cert.crt:/etc/nginx/ssl/cert.crt
      #- ./dev-key.pem:/etc/nginx/ssl/key.pem
    entrypoint: /usr/local/bin/docker-php-entrypoint-dev
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
    ports:
      - "8080:80"
      - "8443:443"
      - "9001:9001"

# using this named volume ensures db's hang around between "up's"
volumes:
  mysql:
